services:
  main:
    container_name: main
    build:
      context: ./main

    # Set environment variables directly in the compose file
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}

    # Set environment variables based on the .env file
    env_file:
      - .env
    volumes:
      - ./main/src:/app/src
      - ./main/public:/app/public
      - './main:/app:delegated'
      - 'main_tmp:/mnt/tmp'
      - 'main_xdg_cache:/home/node/.cache'
      - 'main_xdg_config:/home/node/.config'
    command: ["/bin/bash"]
    ports:
      - 3001:3001
    stdin_open: true
    tty: true
  # Add more containers below (nginx, postgres, etc.)
volumes:
  main_tmp:
  main_xdg_cache:
  main_xdg_config:
